### ISSUE TITLE
Whitespace is also collapsed within code and pre tags

### ISSUE THREAD

**Issue by Lonami** [mettke/minify-rs#2]
I really enjoy the dependency-less aspect of this library, but unfortunately it seems to come with a cost. It removes whitespace from tags which care about it, such as `<pre>` and `<code>`.

**Comment by mettke** [comment]
Hey @Lonami,

thanks for the Info. Would you mind giving me a detailed (minimal) example to reproduce the problem.
Afterwards I will create a test and push an updated version.

**Comment by Lonami** [comment]
Darn that was a fast response! Here's an example:

```html
<pre>
    should respect this          does it?
</pre>
```

The output of this should be exactly the same, however, it currently turns it into:

```html
<pre> should respect this does it? </pre>
```

**Comment by mettke** [comment]
Ah yes - I see. It will take me a while - but there will be an update soon. 
Thanks for reporting!

**Comment by Lonami** [comment]
The tricky part is recognizing both the opening and closing tag, because there may be arbitrary whitespace between the `<` and the tag name, and the tag name should be case insensitive. And I don't know if there's more edge cases we should worry about.

**Comment by mettke** [comment]
Should be fixed with the newest version. However, I'm not dealing with all the edge cases. What should work is whitespaces between the opening tag `<` but its not case insensitive.
